//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ServiceReferenceCategoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCategoria.IServiceCategoria")]
    public interface IServiceCategoria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCategoria/GetAllCategorias", ReplyAction="http://tempuri.org/IServiceCategoria/GetAllCategoriasResponse")]
        Entities.Models.Categoria[] GetAllCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCategoria/GetAllCategorias", ReplyAction="http://tempuri.org/IServiceCategoria/GetAllCategoriasResponse")]
        System.Threading.Tasks.Task<Entities.Models.Categoria[]> GetAllCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCategoria/GetAllCategoriaById", ReplyAction="http://tempuri.org/IServiceCategoria/GetAllCategoriaByIdResponse")]
        Entities.Models.Categoria GetAllCategoriaById(int IdCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCategoria/GetAllCategoriaById", ReplyAction="http://tempuri.org/IServiceCategoria/GetAllCategoriaByIdResponse")]
        System.Threading.Tasks.Task<Entities.Models.Categoria> GetAllCategoriaByIdAsync(int IdCategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCategoriaChannel : Data.ServiceReferenceCategoria.IServiceCategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCategoriaClient : System.ServiceModel.ClientBase<Data.ServiceReferenceCategoria.IServiceCategoria>, Data.ServiceReferenceCategoria.IServiceCategoria {
        
        public ServiceCategoriaClient() {
        }
        
        public ServiceCategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.Models.Categoria[] GetAllCategorias() {
            return base.Channel.GetAllCategorias();
        }
        
        public System.Threading.Tasks.Task<Entities.Models.Categoria[]> GetAllCategoriasAsync() {
            return base.Channel.GetAllCategoriasAsync();
        }
        
        public Entities.Models.Categoria GetAllCategoriaById(int IdCategoria) {
            return base.Channel.GetAllCategoriaById(IdCategoria);
        }
        
        public System.Threading.Tasks.Task<Entities.Models.Categoria> GetAllCategoriaByIdAsync(int IdCategoria) {
            return base.Channel.GetAllCategoriaByIdAsync(IdCategoria);
        }
    }
}
